name = "Black Order 2.1.0";
picture = "logo_blackorder_ca.paa";
actionName = "GitHub";
action = "https://github.com/acemod/ACE3";
description = "Black Order - Version 2.1.0";logo = "logo_blackorder_ca.paa";
logoOver = "logo_blackorder_ca.paa";
tooltip = "Black Order";
tooltipOwned = "Black Order Owned";
overview = "Black Order...";
author = "Black Order Team";
overviewPicture = "logo_blackorder_ca.paa";
